### ISSUE TITLE
Fail in Build

### ISSUE THREAD

**Issue by 201flaviosilva** [enable3d/enable3d-phaser-project-template#1]
Hey,

I am getting this error on the server after build :)

- I cloned the repository;
- Did `npm install`; 
- And then `npm run build`;
- I opened the index on VS Code on the live server and got this error;
- So I created a page on Netlify with this and the error was the same, ([You can check it here](https://enable3d-fixolas.netlify.app/phaser/template/dist));

```js
Failed to load resource: the server responded with a status of 404 (Not Found)
vendors.711f777ae71a92a8ca55.bundle.js:7002 Uncaught 

Error: failed to load /assets/ammo/ammo.wasm.js
    at HTMLScriptElement.i.onerror (vendors.711f777ae71a92a8ca55.bundle.js:7002) 
```

(Sorry my English 😅)

**Comment by yandeu** [comment]
This is because `npm run build` places the production-ready code inside the `/dist` folder. You should NOT use `npm run build` for development. If you want to run the production build, you have to serve the `/dist` folder as root. Also if you upload your project to a Netlify, you should ONLY upload the `/dist` folder.

I have just added a `npm run serve` script, which will serve the `/dist` folder after build (https://github.com/enable3d/enable3d-phaser-project-template/commit/14c2a5a65ab7ff2188f580ef84e516ce183f8fd6).

Try to run `npm run serve` after `npm run build` to test it.

---

_Btw, try the [Five Server](https://marketplace.visualstudio.com/items?itemName=yandeu.five-server) extension for VSCode instead of Live Server._

**Comment by 201flaviosilva** [comment]
Ya is right, it worked,

I'm sorry, I'm very noob,

Grateful :)
